import { EstimateResponse } from "@/app/api/estimation/route";

export function createEmailContent(results: EstimateResponse, notes: string) {
  const lines: string[] = [];

  lines.push("Cloud cost estimate");
  lines.push(`Pricing snapshot: ${results.pricingAsOf}`);
  lines.push(`Calculated at: ${results.calculatedAt}`);
  lines.push("--------------------------------------------------");

  results.estimates.forEach((est) => {
    lines.push(`${est.provider} (${est.confidence.toUpperCase()})`);
    if (est.regionLabel || est.region) {
      lines.push(`  Region:  ${est.regionLabel ?? est.region}`);
    }
    lines.push(`  Monthly: ${est.monthlyTotal} ${est.currency}`);
    lines.push(`  Daily:   ${est.dailyTotal} ${est.currency}`);

    if (est.assumptions.length) {
      lines.push("  Assumptions:");
      est.assumptions.forEach((a) => lines.push(`    • ${a}`));
    }

    if (est.breakdown.length) {
      lines.push("  Breakdown:");
      est.breakdown.forEach((b) =>
        lines.push(
          `    • ${b.item}: ${b.monthly} ${est.currency} (${b.notes})`,
        ),
      );
    }

    if (est.pricingLinks.length) {
      lines.push("  Pricing links:");
      est.pricingLinks.forEach((link) => lines.push(`    • ${link}`));
    }

    lines.push("--------------------------------------------------");
  });

  if (notes) {
    lines.push("Notes:");
    lines.push(notes);
    lines.push("--------------------------------------------------");
  }

  lines.push("Generated by Cloud Cost Estimation");
  return lines.join("\r\n");
}
